#!/bin/sh -e
# Copyright (c) 2016 The crouton Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
REQUIRES='core'
DESCRIPTION='Basic installation of WordPress on a LEMP stack'
HOSTBIN='wp'
CHROOTBIN='croutonpowerd'
. "${TARGETSDIR:="$PWD"}/common"

# Update database
apt-get update || true

### Install needed packages and configure MySQL 
echo 'mysql-server mysql-server/root_password password password' | debconf-set-selections
echo 'mysql-server mysql-server/root_password_again password password' | debconf-set-selections
install nginx mysql-server php-fpm php-mysql php7.0-xml vim git
wget -O /etc/nginx/sites-enabled/default.conf https://raw.githubusercontent.com/10up/word-salad/master/config/nginx/default.conf

### Install WP-CLI
if [ ! -f '/usr/local/bin/wp' ]; then
	wget -O /tmp/wp-cli.phar https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
	chmod +x /tmp/wp-cli.phar
	mv /tmp/wp-cli.phar /usr/local/bin/wp
fi

### Set up rc.local to start mysql, php, and nginx
cat << EOF > /etc/rc.local
#!/bin/sh -e
export HOME=/etc/mysql
umask 007
[ -d /var/run/mysqld ] || install -m 755 -o mysql -g root -d /var/run/mysqld
/usr/sbin/mysqld &

service nginx start

service php7.0-fpm start 

exit 0
EOF

chmod u+x /etc/rc.local

### Start MySQL
service mysql start

### Install WP
if [ -f '/var/www/wordpress/wp-config.php' ]; then
	echo "WordPress config file found."
else
	echo "WordPress config file not found. Installing..."
	wp core download --path=/var/www/wordpress/ --allow-root
	wp core config --path=/var/www/wordpress/ --dbhost=localhost --dbname=wordpress --dbuser=root --dbpass=password --allow-root
	chown -R www-data /var/www/wordpress/
fi
